version: '3.7'

services:
    microservice:
        build:
            context: ./server
        image: server-app
        container_name: server-app
        restart: unless-stopped
        ports:
            - "8000:8000"
        command: uvicorn main:app --host 0.0.0.0 --port 8000

    redis:
        image: redis
        container_name: redis
        restart: unless-stopped
        volumes:
            - ./redis/data:/data
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        expose:
            - 6379
        command: redis-server /usr/local/etc/redis/redis.conf